### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by K-I-N-G-STAR** [EdisonLeeeee/SAT#1]
您好，在main.py 文件中
attacker_name = 'Nettack'
direct_attack = True
adv_edges = np.load(
    f'adversarial_edges/targeted/{dataset}_{attacker_name}{"_In" if not direct_attack else ""}.npy', allow_pickle=True).item()
targets = np.array(list(adv_edges.keys()))

需要加载 'adversarial_edges/targeted/cora_Nettack.npy' 这个文件，但是我并没有找到该文件，您能帮助我吗

**Comment by EdisonLeeeee** [comment]
数据已经上传到Github了，很抱歉很您带来不便！
